services:
  db_service:
    image: mysql:8.0
    container_name: db_D6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql 
    networks:
      - conseling_net

  app_service:
    build: ./app
    container_name: app_D6
    restart: always
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db_service
    networks:
      - conseling_net

  nginx_service:
    image: nginx:alpine
    container_name: nginx_D6
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - conseling_net

networks:
  conseling_net:
    driver: bridge